services:
  app:
    build: .
    image: ghcr.io/abertagnon/gym-baize:latest
    ports:
      - "127.0.0.1:3001:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
